from typing import Protocol, Self


class UnitOfWork(Protocol):
    def __enter__(self) -> Self: ...

    def __exit__(self, *args): ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
