from typing import Protocol, Self

from revegetator.adapters.repository import BatchRepository


class UnitOfWork(Protocol):
    def __enter__(self) -> Self: ...

    def __exit__(self, *args): ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def batches(self) -> BatchRepository: ...
